tasks:
  # NOTE: below `sudo chmod o+rwx .` - this dot specific "here" directory is different from wildcard in line below!
  - init: | 
      make deps
      docker-compose build
      docker-compose pull
      sudo chmod o+rwx . 
      sudo chmod -R o+rw *
    command: |
      docker-compose up 
# split right so normal terminal can be seen 
    openMode: split-right
# direct open preview   
ports:
# still applied even above implicitly says ignore! 
# NOTE: can not have more than two using onOpen: open-preview
  - port: 8041
    visibility: private
    onOpen: open-preview

jetbrains:
  phpstorm:
    plugins:
      - com.intellij.lang.jsgraphql
      - org.sonarlint.idea
    prebuilds:
      version: stable